/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefrigeratorRepairRouteImport } from './routes/refrigerator-repair'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'

const RefrigeratorRepairRoute = RefrigeratorRepairRouteImport.update({
  id: '/refrigerator-repair',
  path: '/refrigerator-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/refrigerator-repair': typeof RefrigeratorRepairRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/refrigerator-repair': typeof RefrigeratorRepairRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/refrigerator-repair': typeof RefrigeratorRepairRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/refrigerator-repair' | '/services/$service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/refrigerator-repair' | '/services/$service'
  id: '__root__' | '/' | '/refrigerator-repair' | '/services/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RefrigeratorRepairRoute: typeof RefrigeratorRepairRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refrigerator-repair': {
      id: '/refrigerator-repair'
      path: '/refrigerator-repair'
      fullPath: '/refrigerator-repair'
      preLoaderRoute: typeof RefrigeratorRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RefrigeratorRepairRoute: RefrigeratorRepairRoute,
  ServicesServiceRoute: ServicesServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
